export const experiments = [
  { 
    title: 'HelloHeart',
    description: 'First demo experiment',
    frontpage: true,
    menu: true,
    icon: 'extension',
    expId: 'HelloHeart', 
    meta: { group:"test"},
  },
  { 
    title: 'Simple Affect',
    description: 'Einführungsexperiment für affektive Paradigmen.',
    frontpage: true,
    menu: true,
    expId: 'SimpleAffect',
    meta: { group:"test"},
  },
  { 
    title: 'Simple Questionaire',
    description: 'Einführungsexperiment für affektive Paradigmen.',
    frontpage: true,
    menu: true,
    expId: 'SimpleQuestionnaire', 
    meta: { group:"test"},
  },  
  { 
    title: 'MBodyDemo',
    description: 'Demo of mBody screens and options',
    frontpage: true,
    menu: true,
    icon: 'extension',
    expId: 'MBodyDemo', 
    meta: { group:"test"},
  },
  { 
    title: 'BodyParts',
    description: 'Demo of mBody screens and options',
    frontpage: true,
    menu: true,
    icon: 'extension',
    expId: 'BodyParts', 
    meta: { group:"test"},
  },

]